//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        public int Sales_ID { get; set; }
        public int Product_ID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Sales_Date { get; set; }
        public int Customer_ID { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
